version: "3.8"

services:
  hardhat-node:
    image: node:22
    container_name: hardhat-node
    working_dir: /app
    volumes:
      - .:/app
    command: npx hardhat node
    ports:
      - "8545:8545"

  frontend:
    image: node:22
    container_name: dao-frontend
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - hardhat-node
